### ISSUE TITLE
Latest version problem with --bundle

### ISSUE THREAD

**Issue by mid787** [ddfreiling/tns-ng-deeplink#4]
@ddfreiling 
There is a problem  running this with `--bundle` with the `deep-link` code . 

In the [webpack json](https://gist.github.com/RoyiNamir/af04e48a6b867f3ef8426ddd3a5a1bd3) file I  have : 
```
 const appComponents = [
        "tns-core-modules/ui/frame",
        "tns-core-modules/ui/frame/activity",
        resolve(__dirname, "app/activity.android.ts"),        <--------
    ];
```

In the [activity itself I have](https://gist.github.com/c13cdf53f2ab81e51bec5e797dc7ac7a)  ( deep link): 
```
export var AndroidOnRouteToURL = new ReplaySubject<string>();

@JavaProxy("org.myApp.MainActivity")
class Activity extends android.support.v7.app.AppCompatActivity {
...
```
And in the[ deep-link service we have](https://gist.github.com/42e531b8ca57aa9e8baa038634230764) : 

```
 OnRouteToURL = require('./activity').AndroidOnRouteToURL;
```

If I remove(!!) that line ^ and do `tns run android --bundle` ,  Everything is OK.

But If  I keep that line , I get : 
```
ERROR in ./activity.ts
Module build failed: Error: C:\r\a\app\activity.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\r\a\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\angular_compiler_plugin.ts:951:15)
    at plugin.done.then (C:\r\a\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\loader.ts:49:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./deep-links.service.ts 5:19-40
 @ ./app.module.ts
 @ ./main.ts

```

How can I solve this ?

I did exactly what @vchimev vchimev told us [here](https://github.com/NativeScript/nativescript-dev-webpack/issues/564#issuecomment-399675425) 

I did as it  says [here]( https://github.com/ddfreiling/tns-ng-deeplink/blob/master/app/activity.android.ts#L4) : AND  [here]( https://github.com/ddfreiling/tns-ng-deeplink/blob/master/app/app.component.ts#L14)

**Comment by ddfreiling** [comment]
@RoyiNamir Did you solve this? I think in my current project - which works fine with bundling - I just flipped the responsibility around, so that the activity emits to a ReplaySubject on another class/service.

The problem you experience stems from not being able to `require` the activity by filename, which no longer exists, because it has been bundled into bundle.js

**Comment by mid787** [comment]
@ddfreiling  Well.... where to start....

_First of all , I'm talking about the most latest ( stable) versions of all ( ns , webpack - which changed dramatically,typescript-dev etc)_

After investigation , it seems that webpack is problematic . ( or maybe it's me , but i'm not sure.)
`require` the `delegate` or `require` the `activity` file is not working anymore. ( it did work in older version of webpack and tns)

The workaround i've used is to remove the `require` and to "fool" the system by `d.ts` files.

What's that mean ? answer : 

the **activity.android.ts** still return the subject : 

![image](https://user-images.githubusercontent.com/2842123/42207409-8524b5c6-7eb2-11e8-89d1-bc98e61f7fec.png)

but I've also added **activity.d.ts** file : 

![image](https://user-images.githubusercontent.com/2842123/42207463-a2b19bc2-7eb2-11e8-968b-ad69efeaeaab.png)


Which includes the "interface contract" props.

But now , instead of **require** it , I can import(!!!!!!!!) it without .ios .android  , because of the d.ts help 
 
![image](https://user-images.githubusercontent.com/2842123/42207544-d7d04fe2-7eb2-11e8-9616-af01e60b8cb9.png)


So basically there is no require anymore.

# but FYI

There is still a problem with declaring the activity in the new webpack with absolute files path

I had to declare the activity in webpackjson file  as : 
```
 const appComponents = [
        "tns-core-modules/ui/frame",
        "tns-core-modules/ui/frame/activity",
        "./activity.android.ts"
        
    ];
```

becuase this : didn't work ( [and it should according to this comment](https://github.com/NativeScript/nativescript-dev-webpack/issues/564#issuecomment-399675425)) 
```
  const appComponents = [
        "tns-core-modules/ui/frame",
        "tns-core-modules/ui/frame/activity",
        resolve(__dirname, "app/activity.android.ts")
        
    ];
```


which is why I've opened a new issue : [**here**](https://github.com/NativeScript/nativescript-dev-webpack/issues/592#event-1713322132) 

I'd be happy if you can see the issue and the project demo at the bottom and try if it fails at your side ( which chaning the webpack config :  `  resolve(__dirname, "app/activity.android.ts")` vs  `  "./activity.android.ts"` ( windows).

All along the way I've used webpack 0.14.2 which should already fixed that path problem[ since merged has already been done.
](https://github.com/NativeScript/nativescript-dev-webpack/pull/578)
